import Link from "next/link";
import { StudentShell } from "./StudentShell";
export function Dashboard(){return <StudentShell title="Dashboard"><div className="dashboard">
 <section className="welcome"><div><span className="kicker">MONDAY, 28 JULY</span><h2>Welcome back, Rahul.</h2><p>Level 19 is closer than you think.</p></div><div className="weekly"><span>WEEKLY GOAL</span><b>4 / 5 days</b><div><i/><i/><i/><i/><i className="off"/></div></div></section>
 <section className="continue-card"><div className="level-disc"><small>LEVEL</small><b>18</b><span>65%</span></div><div className="continue-copy"><span>CURRENT LEVEL • SKILL DEVELOPMENT</span><h2>Responsive Web Interfaces</h2><p>Build interfaces that adapt beautifully to every screen and interaction.</p><div className="mission-progress"><i style={{width:"65%"}}/></div><small>3 of 5 missions complete</small><Link className="btn btn-light" href="/dashboard/journey">Continue journey →</Link></div><div className="next-reward"><span>NEXT REWARD</span><div>✦</div><b>BUILDER<br/>CERTIFICATE</b><small>Level 20 • 2 levels away</small></div></section>
 <section className="dash-grid"><article className="daily"><span className="kicker">TODAY’S MISSION</span><h3>Responsive navigation</h3><p>Build an accessible mobile menu that feels effortless.</p><footer><b>25 MIN</b><b>+180 XP</b><button>Start mission →</button></footer></article>
 <article className="stat streak"><span>🔥</span><b>12</b><small>DAY STREAK</small><p>Personal best: 16</p></article><article className="stat xp"><span>⚡</span><b>2,450</b><small>TOTAL XP</small><p>550 until next rank</p></article>
 <article className="project-card"><small>CURRENT PROJECT</small><h3>Campus Events Platform</h3><div className="project-screen"><i/><i/><i/></div><footer><span>72% complete</span><b>Continue →</b></footer></article>
 <article className="mentor-card"><span>NEXT MENTOR SESSION</span><h3>Portfolio teardown</h3><p>Thursday • 6:30 PM</p><div><i>AM</i><span>With Ananya Mehta<br/><small>Frontend Mentor</small></span></div><button>Add reminder</button></article>
 <article className="achievement-card"><span>RECENT ACHIEVEMENT</span><div>◇</div><h3>Consistency Builder</h3><p>10-day learning streak</p></article></section></div></StudentShell>}
